// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pertamina.SolutionTemplate.Infrastructure.Persistence.SqlServer;

#nullable disable

namespace Pertamina.SolutionTemplate.Infrastructure.Persistence.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerSolutionTemplateDbContext))]
    [Migration("20220820065920_SqlServerSolutionTemplateDbContext_001_InitialSchema")]
    partial class SqlServerSolutionTemplateDbContext_001_InitialSchema
    {
        String strschemadot = ".SolutionTemplate.";
        String strschema1 = "SolutionTemplate";
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "0.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);
            modelBuilder.Entity("Pertamina" + strschemadot + "Domain.Entities.Data", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                b.Property<string>("Code_Apps")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Application_Area")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Application_Name")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Application_Type")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Description")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Capability")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Application_Data")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Diagram_Context")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Diagram_Physical")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Creator")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Level_1")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Level_2")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Utilization")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Application_Status")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Application_License")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Application_Ats")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Application_Package")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("User_Management_Integration")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("User_Manual_Document")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Business_Owner_PIC")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Business_Owner")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Developer")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Link_Application")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Users")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Start_Development")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Start_Implementation")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Criticality")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Holding_Area")
                   .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset>("Created")
                   .HasColumnType("datetimeoffset");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)");

                b.HasKey("Id");

                b.ToTable("Data", strschema1);
            });

#pragma warning restore 612, 618
        }
    }
}
