// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pertamina.SolutionTemplate.Infrastructure.Persistence.SqlServer;

#nullable disable

namespace Pertamina.SolutionTemplate.Infrastructure.Persistence.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerSolutionTemplateDbContext))]
    partial class SqlServerSolutionTemplateDbContextModelSnapshot : ModelSnapshot
    {
        String strschema = ".SolutionTemplate.";
        String strschema1 = "SolutionTemplate";
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "0.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Pertamina" + strschema + "Domain.Entities.Data", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                b.Property<string>("Code_Apps")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Application_Area")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Application_Name")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Application_Type")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Description")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Capability")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Application_Data")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Diagram_Context")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Diagram_Physical")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Creator")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Level_1")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Level_2")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Utilization")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Application_Status")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Application_License")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Application_Ats")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Application_Package")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("User_Management_Integration")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("User_Manual_Document")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Business_Owner_PIC")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Business_Owner")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Developer")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Link_Application")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Users")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Start_Development")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Start_Implementation")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Criticality")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Holding_Area")
                   .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset>("Created")
                   .HasColumnType("datetimeoffset");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)");

                b.HasKey("Id");

                b.ToTable("Data", strschema1);
            });

            modelBuilder.Entity("Pertamina" + strschema + "Domain.Entities.App", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("Modified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Apps", strschema1);
                });

            modelBuilder.Entity("Pertamina" + strschema + "Domain.Entities.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientApplicationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FromIpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Audits", strschema1);
                });

            modelBuilder.Entity("Pertamina" + strschema + "Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EcmContentId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("JrdpYear")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("Modified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StorageFileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TopicCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Documents", strschema1);
                });

            modelBuilder.Entity("Pertamina" + strschema + "Domain.Entities.SupportEngineer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("Modified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SupportEngineers", strschema1);
                });

            modelBuilder.Entity("Pertamina" + strschema + "Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobIdForAutoClose")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("Modified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SeverityLevel")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SupportEngineerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("SupportEngineerId");

                    b.ToTable("Tickets", strschema1);
                });

            modelBuilder.Entity("Pertamina" + strschema + "Domain.Entities.TicketAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("Modified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StorageFileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketAttachments", strschema1);
                });

            modelBuilder.Entity("Pertamina" + strschema + "Domain.Entities.TicketLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketLogs", strschema1);
                });

            modelBuilder.Entity("Pertamina" + strschema + "Domain.Entities.TicketMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketMessages", strschema1);
                });

            modelBuilder.Entity("Pertamina" + strschema + "Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSmsNotificationEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("Modified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OtpSecret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtpUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users", strschema1);
                });

            modelBuilder.Entity("Pertamina" + strschema + "Domain.Entities.Audit", b =>
                {
                    b.OwnsOne("Pertamina" + strschema + "Base.ValueObjects.Geolocation", "FromGeolocation", b1 =>
                        {
                            b1.Property<Guid>("AuditId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Accuracy")
                                .HasColumnType("float")
                                .HasColumnName("Accuracy");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Longitude");

                            b1.HasKey("AuditId");

                            b1.ToTable("Audits", strschema1);

                            b1.WithOwner()
                                .HasForeignKey("AuditId");
                        });

                    b.Navigation("FromGeolocation");
                });

            modelBuilder.Entity("Pertamina" + strschema + "Domain.Entities.SupportEngineer", b =>
                {
                    b.HasOne("Pertamina" + strschema + "Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pertamina" + strschema + "Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Pertamina" + strschema + "Domain.Entities.App", "App")
                        .WithMany("Tickets")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pertamina" + strschema + "Domain.Entities.User", "Creator")
                        .WithMany("Tickets")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pertamina" + strschema + "Domain.Entities.SupportEngineer", "SupportEngineer")
                        .WithMany("Tickets")
                        .HasForeignKey("SupportEngineerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("App");

                    b.Navigation("Creator");

                    b.Navigation("SupportEngineer");
                });

            modelBuilder.Entity("Pertamina" + strschema + "Domain.Entities.TicketAttachment", b =>
                {
                    b.HasOne("Pertamina" + strschema + "Domain.Entities.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Pertamina" + strschema + "Domain.Entities.TicketLog", b =>
                {
                    b.HasOne("Pertamina" + strschema + "Domain.Entities.Ticket", "Ticket")
                        .WithMany("Logs")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Pertamina" + strschema + "Domain.Entities.TicketMessage", b =>
                {
                    b.HasOne("Pertamina" + strschema + "Domain.Entities.Ticket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Pertamina" + strschema + "Domain.Entities.App", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Pertamina" + strschema + "Domain.Entities.SupportEngineer", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Pertamina" + strschema + "Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Logs");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Pertamina" + strschema + "Domain.Entities.User", b =>
                {
                    b.Navigation("Tickets");
                });
            modelBuilder.Entity("Pertamina" + strschema + "DraftHistoricalApplicationStatusPhase", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<string>("ApprovedStatus")
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("Approved_Status");

                b.Property<string>("CodeApps")
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("Code_Apps");

                b.Property<DateTimeOffset?>("Created")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Date")
                    .HasColumnType("datetimeoffset");

                b.Property<DateTimeOffset?>("Day")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("IsApproved")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("IsDeleted")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Keterangan")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Modified")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("ModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Month")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("Phase")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Source")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Year")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.ToTable("DraftHistoricalApplicationStatusPhase", "SolutionTemplate");
            });
            modelBuilder.Entity("Pertamina" + strschema + "ApplicationArea", b =>
            {
                b.Property<DateTimeOffset?>("Created")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Id")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("IsDeleted")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Keterangan")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Modified")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("ModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nama")
                    .HasColumnType("nvarchar(max)");

                b.ToTable("ApplicationArea", "SolutionTemplate");
            });

            modelBuilder.Entity("Pertamina" + strschema + "ApplicationCapabilityLevel1", b =>
            {
                b.Property<DateTimeOffset?>("Created")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Id")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("IsDeleted")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Keterangan")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Modified")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("ModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nama")
                    .HasColumnType("nvarchar(max)");

                b.ToTable("ApplicationCapabilityLevel1", "SolutionTemplate");
            });

            modelBuilder.Entity("Pertamina" + strschema + "ApplicationCapabilityLevel2", b =>
            {
                b.Property<DateTimeOffset?>("Created")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Id")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("IsDeleted")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Keterangan")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Level1")
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("Level_1");

                b.Property<DateTimeOffset?>("Modified")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("ModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nama")
                    .HasColumnType("nvarchar(max)");

                b.ToTable("ApplicationCapabilityLevel2", "SolutionTemplate");
            });

            modelBuilder.Entity("Pertamina" + strschema + "ApplicationCriticality", b =>
            {
                b.Property<DateTimeOffset?>("Created")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Id")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("IsDeleted")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Keterangan")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Modified")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("ModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nama")
                    .HasColumnType("nvarchar(max)");

                b.ToTable("ApplicationCriticality", "SolutionTemplate");
            });

            modelBuilder.Entity("Pertamina" + strschema + "ApplicationLicense", b =>
            {
                b.Property<DateTimeOffset?>("Created")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Id")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("IsDeleted")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Keterangan")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Modified")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("ModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nama")
                    .HasColumnType("nvarchar(max)");

                b.ToTable("ApplicationLicense", "SolutionTemplate");
            });

            modelBuilder.Entity("Pertamina" + strschema + "ApplicationPackage", b =>
            {
                b.Property<DateTimeOffset?>("Created")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Id")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("IsDeleted")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Keterangan")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Modified")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("ModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nama")
                    .HasColumnType("nvarchar(max)");

                b.ToTable("ApplicationPackage", "SolutionTemplate");
            });

            modelBuilder.Entity("Pertamina" + strschema + "ApplicationStatus", b =>
            {
                b.Property<DateTimeOffset?>("Created")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Id")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("IsDeleted")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Keterangan")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Modified")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("ModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nama")
                    .HasColumnType("nvarchar(max)");

                b.ToTable("ApplicationStatus", "SolutionTemplate");
            });

            modelBuilder.Entity("Pertamina" + strschema + "ApplicationStatusPhase", b =>
            {
                b.Property<DateTimeOffset?>("Created")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Id")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("IsDeleted")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Keterangan")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Modified")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("ModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nama")
                    .HasColumnType("nvarchar(max)");

                b.ToTable("ApplicationStatusPhase", "SolutionTemplate");
            });

            modelBuilder.Entity("Pertamina" + strschema + "ApplicationType", b =>
            {
                b.Property<DateTimeOffset?>("Created")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Id")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("IsDeleted")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Keterangan")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Modified")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("ModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nama")
                    .HasColumnType("nvarchar(max)");

                b.ToTable("ApplicationType", "SolutionTemplate");
            });

            modelBuilder.Entity("Pertamina" + strschema + "ApplicationUserManagement", b =>
            {
                b.Property<DateTimeOffset?>("Created")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Id")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("IsDeleted")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Keterangan")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Modified")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("ModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nama")
                    .HasColumnType("nvarchar(max)");

                b.ToTable("ApplicationUserManagement", "SolutionTemplate");
            });

            modelBuilder.Entity("Pertamina" + strschema + "ApplicationUtilization", b =>
            {
                b.Property<DateTimeOffset?>("Created")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Id")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("IsDeleted")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Keterangan")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Modified")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("ModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nama")
                    .HasColumnType("nvarchar(max)");

                b.ToTable("ApplicationUtilization", "SolutionTemplate");
            });
            modelBuilder.Entity("Pertamina" + strschema + "DraftHistoricalAppPhase", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<string>("ApprovedStatus")
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("Approved_Status");

                b.Property<string>("CodeApps")
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("Code_Apps");

                b.Property<DateTimeOffset?>("Created")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Date")
                    .HasColumnType("datetimeoffset");

                b.Property<DateTimeOffset?>("Day")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("IsApproved")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("IsDeleted")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Keterangan")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Modified")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("ModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Month")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("Phase")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Source")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Reason")
                   .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Year")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.ToTable("DraftHistoricalApplicationStatusPhase", "SolutionTemplate");
            });

            modelBuilder.Entity("Pertamina" + strschema + "HistoricalAppPhase", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<string>("CodeApps")
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("Code_Apps");

                b.Property<DateTimeOffset?>("Created")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Date")
                    .HasColumnType("datetimeoffset");

                b.Property<DateTimeOffset?>("Day")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("IsDeleted")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Keterangan")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Modified")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("ModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Month")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("Phase")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Year")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.ToTable("HistoricalApplicationStatusPhase", "SolutionTemplate");
            });




#pragma warning restore 612, 618
        }
    }
}
